// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddttwqzfbzjntxieeusd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkdHR3cXpmYnpqbnR4aWVldXNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMjc5MDcsImV4cCI6MjA3MjYwMzkwN30.GYw7o2zt33NmJwLKnRf4fS3GnYMTJPeQFncbaepHofs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});